version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing dependencies with Java 8...
      - mvn install -DskipTests

  build:
    commands:
      - echo Building project with Maven...
      - mvn package

artifacts:
  files:
    - target/*.jar
