version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - mvn install -DskipTests
  build:
    commands:
      - echo Building project...
      - mvn package

artifacts:
  files:
    - target/*.jar
